//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedAH
    {
        public int accountHolderID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string passwordsalt { get; set; }
        public string passwordhash { get; set; }
        public string pinsalt { get; set; }
        public string pinhash { get; set; }
        public System.DateTime DOB { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string firstLineaddr { get; set; }
        public string cityOrTown { get; set; }
        public string postcode { get; set; }
    }
}
